name: Daily update
on: [workflow_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fetch_api/requirements.txt
      - name: Run update script
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: python fetch_api/update.py
